// Generated by CoffeeScript 1.4.0
(function() {
  var LOOPS, MAX_LOOP_COUNT, Module, ModulePath, addPlugin, async, autoprefixer, booster, fs, getSource, pluginsDir, postcss, syspath, utils, _,
    _this = this;

  _ = require('underscore');

  async = require('async');

  autoprefixer = require('autoprefixer');

  fs = require('fs');

  postcss = require('postcss');

  syspath = require('path');

  utils = require('../util');

  exports.booster = booster = require('./module/booster');

  Module = require("./module/module").Module;

  Module.booster = booster;

  ModulePath = require('./module/path').ModulePath;

  exports.path = Module.path;

  /* ---------------------------
      插件系统
  */


  exports.getContentType = function(url) {
    return Module.getContentType(syspath.extname(url));
  };

  addPlugin = function(extName, plugin) {
    return Module.addExtensionPlugin(extName, plugin);
  };

  pluginsDir = syspath.join(syspath.dirname(__filename), "plugins");

  utils.path.each_directory(pluginsDir, function(filepath) {
    var extname, type;
    extname = syspath.extname(filepath);
    type = "." + syspath.basename(filepath, extname);
    return addPlugin(type, require(filepath));
  });

  ModulePath.getCompile(process.cwd(), './');

  /* -----------------------
      export
  */


  LOOPS = {};

  MAX_LOOP_COUNT = 70;

  getSource = function(module, options, callback) {
    return module.analyze(function(err) {
      var USED_MODULES, arr, deps, sub_module, _i, _len, _ref, _tmp;
      if (err) {
        callback(err);
        return;
      }
      arr = [];
      USED_MODULES = options.use_modules;
      if (options.render_dependencies) {
        module.getSourceWithoutDependencies = options.render_dependencies;
      }
      deps = [];
      if (options.no_dependencies !== true) {
        _ref = module.depends;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          sub_module = _ref[_i];
          _tmp = function(sub_module) {
            var _this = this;
            return function(seriesCallback) {
              LOOPS[sub_module.guid] = (LOOPS[sub_module.guid] || 0) + 1;
              if (LOOPS[sub_module.guid] > MAX_LOOP_COUNT) {
                seriesCallback("出现循环调用，请检查 " + sub_module.path.uri + " 的引用");
              }
              if (USED_MODULES[sub_module.guid]) {
                utils.proc.setImmediate(seriesCallback);
                return;
              }
              return getSource(sub_module, options, function(e, txt) {
                arr.push(txt);
                return utils.proc.setImmediate(function() {
                  return seriesCallback(e);
                });
              });
            };
          };
          deps.push(_tmp(sub_module));
        }
      }
      return async.series(deps, function(err) {
        var c, plugin, source, _ref1, _ref2;
        if (err) {
          callback(err);
          return null;
        }
        source = module.getSourceWithoutDependencies();
        c = (_ref1 = module.config.config) != null ? (_ref2 = _ref1.root) != null ? _ref2.autoprefixer : void 0 : void 0;
        if (_.isObject(c) && module.iscss) {
          plugin = autoprefixer(c);
          return postcss([plugin]).process(source).then(function(out) {
            arr.push(out.css);
            USED_MODULES[module.guid] = 1;
            return callback(null, arr.join(utils.file.NEWLINE));
          })['catch'](function(out) {
            console.error('\n%s %s', syspath.relative(process.cwd(), module.path.uri), out.message);
            return process.exit(1);
          });
        }
        arr.push(source);
        USED_MODULES[module.guid] = 1;
        return callback(null, arr.join(utils.file.NEWLINE));
      });
    });
  };

  /*
   options {
      // 依赖的文件列表(fullpath)
      dependencies_filepath_list : []
      // 使用非依赖模式
      no_dependencies : false ,
      // 非依赖模式的生成方案
      render_dependencies : function ,
      // 根模块文件路径(可有可无,如果没有则默认当前处理文件为root_module)
      root_module_path : ""
      // 开发环境
      environment : "local" / "dev" / "prd"
   }
  */


  exports.compile = function(filepath, options, doneCallback) {
    var module, use_modules, _done, _iter, _list;
    LOOPS = {};
    if (arguments.length === 3) {
      options = options || {};
      doneCallback = doneCallback;
    } else if (arguments.length === 2) {
      doneCallback = options;
      options = {};
    }
    use_modules = {};
    module = Module.parse(filepath, options, null, Module.parse(options.root_module_path || filepath));
    _list = options.dependencies_filepath_list || [];
    _iter = function(dep_path, seriesCallback) {
      var parent_module;
      parent_module = new Module(dep_path, options);
      return parent_module.getDependenciesURI(function(err, module_guids) {
        if (!err) {
          _.extend(use_modules, module_guids);
        }
        return utils.proc.setImmediate(function() {
          return seriesCallback(err);
        });
      });
    };
    _done = function(err) {
      if (err) {
        doneCallback(err);
        return;
      }
      return getSource(module, {
        use_modules: use_modules,
        no_dependencies: !!options.no_dependencies,
        render_dependencies: options.render_dependencies
      }, function(err, result) {
        return doneCallback(err, result, module);
      });
    };
    return utils.async.series(_list, _iter, _done);
  };

}).call(this);
