// Generated by CoffeeScript 1.4.0
(function() {
  var PARAM_CACHE, charset, compiler, dns, helper_reverse, mime_config, qs, sysfs, syspath, sysurl, toMD5, toPARAM, urlrouter, utils, writeHeader;

  compiler = require("../compiler/compiler");

  dns = require("dns");

  helper_reverse = require("./helper_reverse");

  qs = require("querystring");

  sysfs = require("fs");

  syspath = require("path");

  sysurl = require("url");

  urlrouter = require("urlrouter");

  utils = require("../util");

  mime_config = {
    ".js": "application/javascript",
    ".css": "text/css"
  };

  charset = ";charset=UTF-8";

  PARAM_CACHE = {};

  toMD5 = function(str) {
    var m;
    m = utils.md5(str).toString().slice(9).slice(0, 16);
    PARAM_CACHE[m] = str;
    return m;
  };

  toPARAM = function(md5str) {
    return PARAM_CACHE[md5str];
  };

  writeHeader = function(res, code, type) {
    return res.writeHead(code, {
      'Content-Type': mime_config[type] + charset,
      'Server': 'Fekit - Local File'
    });
  };

  module.exports = function(options) {
    var ROOT, combine, fekitRouter, no_combine, port, protocol,
      _this = this;
    ROOT = options.cwd;
    protocol = options.ssl ? "https" : "http";
    port = options.port && options.port !== "80" ? ":" + options.port : "";
    if (options.boost) {
      utils.logger.log("已启动加速模式");
    }
    helper_reverse.load(options);
    no_combine = function(path, parents, host, params, doneCallback) {
      var conf, ctx, custom_script, custom_script_path, render_func, _ref, _ref1;
      if (params["no_dependencies"] === "true") {
        return compiler.compile(path, {
          dependencies_filepath_list: parents,
          no_dependencies: true,
          root_module_path: params["root"],
          environment: 'local'
        }, doneCallback);
      } else {
        conf = utils.config.parse(path);
        custom_script = (_ref = conf.root) != null ? (_ref1 = _ref.development) != null ? _ref1.custom_render_dependencies : void 0 : void 0;
        custom_script_path = utils.path.join(conf.fekit_root_dirname, custom_script);
        host = host.replace(/:\d+/, "");
        if (custom_script && utils.path.exists(custom_script_path)) {
          ctx = utils.proc.requireScript(custom_script_path);
          render_func = function() {
            var partial, _path;
            _path = this.path.getFullPath().replace(ROOT, "").replace(/\\/g, '/').replace('/src/', '/prd/');
            partial = ("" + protocol + "://" + host + port + _path + "?") + toMD5("no_dependencies=true&root=" + (encodeURIComponent(path)));
            return ctx.render({
              type: this.path.getContentType(),
              path: this.path.getFullPath(),
              url: partial,
              base_path: path,
              base_params: params
            });
          };
        } else {
          render_func = function() {
            var partial, _path;
            _path = this.path.getFullPath().replace(ROOT, "").replace(/\\/g, '/').replace('/src/', '/prd/');
            partial = ("" + protocol + "://" + host + port + _path + "?") + toMD5("no_dependencies=true&root=" + (encodeURIComponent(path)));
            switch (this.path.getContentType()) {
              case "javascript":
                return "document.write('<script src=\"" + partial + "\"></script>');";
              case "css":
                return "@import url('" + partial + "');";
            }
          };
        }
        return compiler.compile(path, {
          dependencies_filepath_list: parents,
          render_dependencies: render_func,
          environment: 'local'
        }, doneCallback);
      }
    };
    combine = function(path, parents, doneCallback) {
      return compiler.compile(path, {
        dependencies_filepath_list: parents,
        environment: 'local'
      }, doneCallback);
    };
    return fekitRouter = urlrouter(function(app) {
      return app.get(utils.UrlConvert.PRODUCTION_REGEX, function(req, res, next) {
        var cache, config, ctype, host, is_deps, p, params, srcpath, url, urlconvert, _render;
        host = req.headers['host'];
        url = sysurl.parse(req.url);
        p = syspath.join(ROOT, url.pathname);
        params = qs.parse(toPARAM(url.query) || url.query);
        is_deps = params["no_dependencies"] === "true";
        if (utils.path.exists(p) && utils.path.is_directory(p)) {
          next();
          return;
        }
        urlconvert = new utils.UrlConvert(p, ROOT);
        srcpath = urlconvert.to_src();
        srcpath = compiler.path.findFileWithoutExtname(srcpath);
        utils.logger.trace("由 PRD " + req.url + " 解析至 SRC " + srcpath);
        switch (compiler.getContentType(urlconvert.uri)) {
          case "javascript":
            ctype = ".js";
            break;
          case "css":
            ctype = ".css";
            break;
          default:
            ctype = "";
        }
        if (options.boost) {
          cache = compiler.booster.get_compiled_cache(srcpath, is_deps);
          if (cache) {
            writeHeader(res, 200, ctype);
            res.end(cache);
            return;
          }
        }
        _render = function(err, txt, module) {
          if (err) {
            writeHeader(res, 500, ctype);
            utils.logger.error(err);
            return res.end(err);
          } else {
            writeHeader(res, 200, ctype);
            compiler.booster.watch(module);
            compiler.booster.set_compiled_cache(srcpath, txt, is_deps);
            return res.end(txt);
          }
        };
        if (utils.path.exists(srcpath)) {
          config = new utils.config.parse(srcpath);
          return config.findExportFile(srcpath, function(path, parents) {
            if (options.noexport || is_deps) {
              path = srcpath;
            }
            if (path) {
              if (options.combine) {
                return combine(path, parents, _render);
              } else {
                return no_combine(path, parents, host, params, _render);
              }
            } else {
              writeHeader(res, 404, ctype);
              return res.end("请确认文件 " + url.pathname + " 存在于 fekit.config 的 export 中。");
            }
          });
        } else {
          if (options.reverse && helper_reverse.exists(host)) {
            return helper_reverse.request(req.headers, protocol, host, port, url.pathname, res, ctype);
          } else {
            writeHeader(res, 404, ctype);
            return res.end("文件不存在 " + url.pathname + "。");
          }
        }
      });
    });
  };

}).call(this);
