// Generated by CoffeeScript 1.4.0
(function() {
  var rewrite, _routeRules;

  rewrite = require("connect-url-rewrite");

  _routeRules = function(options) {
    var list, n, r, rs, _i, _len;
    list = [];
    rs = [].concat(options.route || []);
    for (_i = 0, _len = rs.length; _i < _len; _i++) {
      n = rs[_i];
      r = n.split(":");
      list.push("" + r[0] + " " + r[1]);
      utils.logger.log("已由 " + r[0] + " 转发至 " + r[1]);
    }
    return list;
  };

  module.exports = function(options) {
    return rewrite(_routeRules(options));
  };

}).call(this);
