// Generated by CoffeeScript 1.4.0
(function() {
  var coffee;

  coffee = require('coffee-script');

  exports.contentType = "javascript";

  exports.process = function(txt, path, cb) {
    try {
      return cb(null, coffee.compile(txt));
    } catch (err) {
      return cb(err);
    }
  };

}).call(this);
