// Generated by CoffeeScript 1.4.0
(function() {
  var crypto, pathToInt, _;

  crypto = require('crypto');

  _ = require('underscore');

  _.str = require('underscore.string');

  /*
      分析 background-image 的图片，将其分发到不同的域名中
      多域名控制格式为
      @domain_mapping source.qunar.com => img1.qunarzz.com img2.qunarzz.com img3.qunarzz.com img4.qunarzz.com
  */


  exports.ddns = function(css_code, module) {
    var RE_DOMAIN, conf, fileconfig, r, root_fekit_config, _dms, _map, _ori, _ref, _ref1, _ref2, _ref3, _ref4;
    root_fekit_config = ((_ref = module.root_module) != null ? (_ref1 = _ref.config) != null ? (_ref2 = _ref1.config) != null ? _ref2.root : void 0 : void 0 : void 0) || {};
    fileconfig = module.root_module.config.config.getExportFileConfig(module.root_module.path.getFullPath());
    if (fileconfig != null ? fileconfig.domain_mapping : void 0) {
      r = fileconfig != null ? fileconfig.domain_mapping : void 0;
    } else if (root_fekit_config != null ? (_ref3 = root_fekit_config.export_global_config) != null ? _ref3.domain_mapping : void 0 : void 0) {
      r = root_fekit_config != null ? (_ref4 = root_fekit_config.export_global_config) != null ? _ref4.domain_mapping : void 0 : void 0;
    } else {
      r = "@domain_mapping source.qunar.com => simg1.qunarzz.com";
    }
    conf = r.split('=>');
    if (!_.str.trim(conf[0])) {
      return css_code;
    }
    if (!_.str.trim(conf[1])) {
      return css_code;
    }
    _ori = _.str.trim(conf[0]).replace(/\s+/g, ' ').split(' ');
    RE_DOMAIN = new RegExp("(http://)(" + _ori.join('|').replace(/\./g, '\\.') + ")(/[^\"'\\s\\)]+)", "g");
    _dms = _.str.trim(conf[1]).replace(/\s+/g, ' ').split(' ');
    _map = {};
    return css_code.replace(RE_DOMAIN, function($0, http, domain, path) {
      var _idx;
      if (_map[$0]) {
        return http + _dms[_map[$0]] + path;
      } else {
        _idx = pathToInt($0, _dms.length);
        _map[$0] = _idx;
        return http + _dms[_idx] + path;
      }
    });
  };

  /*
  exports.omit_protocol = ( css_code , module ) ->
  
      root_fekit_config = module.root_module.config.config.root
  
      return css_code unless root_fekit_config?.export_global_config?.domain_mapping
  */


  exports.contentType = "css";

  exports.process = function(txt, path, module, cb) {
    return cb(null, exports.ddns(txt, module));
  };

  pathToInt = function(str, number) {
    var arr, d, st;
    d = crypto.createHash("md5").update(str).digest('hex');
    arr = d.split("");
    st = 0;
    arr.forEach(function(chr, i) {
      var c;
      c = parseInt(chr, 16);
      return st = (st * 16 + c) % number;
    });
    return st;
  };

}).call(this);
