// Generated by CoffeeScript 1.4.0
(function() {
  var Package, babel, es2015, getBabelConfig, react, syspath, utils;

  utils = require('../../util');

  Package = require('../../package');

  syspath = require('path');

  babel = require('babel-core');

  es2015 = require('babel-preset-es2015');

  react = require('babel-preset-react');

  getBabelConfig = function(configPath) {
    var config;
    if (!utils.path.exists(configPath)) {
      return null;
    }
    config = utils.file.io.readJSON(configPath);
    return config;
  };

  exports.contentType = "javascript";

  exports.process = function(txt, path, module, cb) {
    var babelConfig, babel_config_path, basepath, cwd, name;
    try {
      name = syspath.basename(path, '.es');
      cwd = process.cwd();
      basepath = utils.path.closest(cwd, Package.FEKIT_MODULE_DIR, true);
      if (!basepath) {
        basepath = utils.path.closest(cwd, 'fekit.config');
      }
      if (!basepath) {
        basepath = cwd;
      }
      babel_config_path = utils.path.join(basepath, '.babelrc');
      babelConfig = getBabelConfig(babel_config_path);
      if (!babelConfig) {
        babelConfig = {
          presets: [es2015, react]
        };
      }
      txt = (babel.transform(txt, babelConfig)).code;
      return cb(null, txt);
    } catch (err) {
      return cb(err);
    }
  };

}).call(this);
