// Generated by CoffeeScript 1.4.0
(function() {
  var handlebars, syspath;

  syspath = require('path');

  handlebars = require('handlebars');

  exports.contentType = "javascript";

  exports.process = function(txt, path, module, cb) {
    var builded, name;
    try {
      name = syspath.basename(path, '.handlebars');
      txt = handlebars.precompile(txt);
      builded = "if (typeof window.QTMPL === \"undefined\") window.QTMPL = {};\nwindow.QTMPL[\"" + name + "\"] = new window.Handlebars.template(" + txt + ");\nif (typeof module !== \"undefined\") module.exports = window.QTMPL[\"" + name + "\"];";
      return cb(null, builded);
    } catch (err) {
      return cb(err);
    }
  };

}).call(this);
