// Generated by CoffeeScript 1.4.0
(function() {
  var jade, syspath;

  syspath = require('path');

  jade = require('jade');

  exports.contentType = 'javascript';

  exports.process = function(txt, path, module, cb) {
    var builded, name;
    try {
      name = syspath.basename(path, '.jade');
      txt = jade.compileClient(txt, {
        name: ' ',
        filename: path,
        doctype: 'html'
      });
      builded = "if (typeof window.QTMPL === \"undefined\") window.QTMPL = {};\nwindow.QTMPL[\"" + name + "\"] = " + txt + ";\nif (typeof module !== \"undefined\") module.exports = window.QTMPL[\"" + name + "\"];";
      return cb(null, builded);
    } catch (e) {
      return cb(e);
    }
  };

}).call(this);
