// Generated by CoffeeScript 1.4.0
(function() {

  exports.contentType = "javascript";

  exports.process = function(txt, path, module, cb) {
    return cb(null, "module.exports=" + txt);
  };

}).call(this);
