// Generated by CoffeeScript 1.4.0
(function() {
  var babel, es2015, react, syspath;

  syspath = require('path');

  babel = require('babel-core');

  es2015 = require('babel-preset-es2015');

  react = require('babel-preset-react');

  exports.contentType = "javascript";

  exports.process = function(txt, path, module, cb) {
    var name;
    try {
      name = syspath.basename(path, '.jsx');
      txt = (babel.transform(txt, {
        presets: [es2015, react]
      })).code;
      return cb(null, txt);
    } catch (err) {
      return cb(err);
    }
  };

}).call(this);
