// Generated by CoffeeScript 1.4.0
(function() {
  var react;

  react = require("react-tools");

  exports.contentType = "javascript";

  exports.process = function(txt, path, module, cb) {
    var code;
    try {
      code = react.transform(txt);
      return cb(null, code);
    } catch (err) {
      return cb(err);
    }
  };

}).call(this);
