// Generated by CoffeeScript 1.4.0
(function() {
  var reactTools;

  reactTools = require('react-tools');

  exports.contentType = "javascript";

  exports.process = function(txt, path, module, cb) {
    try {
      return cb(null, reactTools.transform(txt));
    } catch (err) {
      return cb(err);
    }
  };

}).call(this);
