// Generated by CoffeeScript 1.4.0
(function() {
  var compiler;

  compiler = require('less');

  exports.contentType = "css";

  exports.process = function(txt, path, cb) {
    var _this = this;
    return compiler.render(txt, function(err, css) {
      return cb(err, css);
    });
  };

}).call(this);
