// Generated by CoffeeScript 1.4.0
(function() {
  var css, less, syspath;

  css = require('./css');

  syspath = require('path');

  less = require('qless');

  exports.contentType = "css";

  exports.process = function(txt, path, module, cb) {
    var dir, parser;
    dir = syspath.dirname(path);
    parser = new less.Parser({
      paths: [dir]
    });
    return parser.parse(txt, function(err, tree) {
      var code;
      if (err) {
        return cb(err.message);
      }
      code = tree.toCSS({
        compress: false
      });
      return cb(null, css.ddns(code, module));
    });
  };

}).call(this);
