// Generated by CoffeeScript 1.4.0
(function() {
  var less, syspath;

  syspath = require('path');

  less = require('less');

  exports.contentType = "css";

  exports.process = function(txt, path, cb) {
    var dir, parser;
    dir = syspath.dirname(path);
    parser = new less.Parser({
      paths: [dir]
    });
    return parser.parse(txt, function(err, tree) {
      if (err) {
        return cb(err.message);
      }
      return cb(null, tree.toCSS({
        compress: false
      }));
    });
  };

}).call(this);
