// Generated by CoffeeScript 1.7.1
(function() {
  var astral, escodegen, esprima;

  esprima = require('esprima');

  escodegen = require('escodegen');

  astral = require('astral')();

  require('astral-angular-annotate')(astral);

  exports.contentType = "javascript";

  exports.process = function(txt, path, module, cb) {
    var ast, code;
    ast = esprima.parse(txt, {
      tolerant: true
    });
    astral.run(ast);
    code = escodegen.generate(ast, {
      format: {
        indent: {
          style: '  '
        }
      }
    });
    return cb(null, code);
  };

}).call(this);
