// Generated by CoffeeScript 1.4.0
(function() {
  var MAP, convertRegexp, css, grep_import, regstr, sass, syspath, utils;

  utils = require('../../util');

  css = require('./css');

  syspath = require('path');

  sass = require('node-sass');

  MAP = {};

  convertRegexp = function(str, flag) {
    str = str.replace(/\s/g, '').replace('{space}', ' ');
    return new RegExp(str, flag);
  };

  regstr = convertRegexp("(\n    ?: [{space}]*@import\\s*\\s*'([^']+)'\\s*\n    |  [{space}]*@import\\s*\\s*\"([^\"]+)\"\\s*\n)\n[{space};]*", "g");

  grep_import = function(txt, basedir) {
    return txt.replace(regstr, function($0, $1, $2) {
      var p;
      p = utils.path.join(basedir, $1 || $2);
      if (MAP[p]) {
        return "";
      } else {
        MAP[p] = true;
        return $0;
      }
    });
  };

  exports.contentType = "css";

  exports.process = function(txt, path, module, cb) {
    var dir, fail, result, succ;
    dir = syspath.dirname(path);
    succ = function(code) {
      return cb(null, css.ddns(code, module));
    };
    fail = function(err) {
      return cb(err);
    };
    try {
      result = sass.renderSync({
        data: txt,
        includePaths: [dir],
        outputStyle: "compressed"
      });
      return succ(result.css.toString());
    } catch (err) {
      return fail(err);
    }
  };

}).call(this);
