// Generated by CoffeeScript 1.4.0
(function() {
  var sass;

  sass = require('sass');

  exports.contentType = "css";

  exports.process = function(txt, path) {
    return sass.render(txt);
  };

}).call(this);
