// Generated by CoffeeScript 1.7.1
(function() {
  var css, sass, syspath;

  css = require('./css');

  syspath = require('path');

  sass = require('node-sass');

  exports.contentType = "css";

  exports.process = function(txt, path, module, cb) {
    var dir, fail, succ;
    dir = syspath.dirname(path);
    succ = function(code) {
      return cb(null, css.ddns(code, module));
    };
    fail = function(err) {
      return cb(err);
    };
    return sass.render({
      data: txt,
      includePaths: [dir],
      success: succ,
      error: fail
    });
  };

}).call(this);
