// Generated by CoffeeScript 1.4.0
(function() {
  var sass;

  sass = require('node-sass');

  exports.contentType = "css";

  exports.process = function(txt, path, cb) {
    var _this = this;
    return sass.render(txt, function(err, css) {
      return cb(err, css);
    });
  };

}).call(this);
