// Generated by CoffeeScript 1.4.0
(function() {
  var syspath;

  syspath = require('path');

  exports.contentType = "javascript";

  exports.process = function(ori_txt, path, module, cb) {
    var code, s, scope;
    s = JSON.stringify;
    scope = path.replace(syspath.join(module.config.config.fekit_root_dirname, 'src/'), '');
    scope = scope.replace(syspath.extname(scope), '');
    scope = scope.split(syspath.sep);
    code = "String." + (scope.join('.')) + " = " + (s(ori_txt)) + ";";
    return cb(null, code);
  };

}).call(this);
