// Generated by CoffeeScript 1.4.0
(function() {
  var syspath;

  syspath = require('path');

  exports.contentType = "javascript";

  exports.process = function(ori_txt, path, module, cb) {
    var code, name, txt;
    name = syspath.basename(path, '.string');
    txt = JSON.stringify(ori_txt);
    code = "if (typeof window.QTMPL === \"undefined\") window.QTMPL = {};\nwindow.QTMPL[\"" + name + "\"] = " + txt + ";\nif (typeof module !== \"undefined\") module.exports = window.QTMPL[\"" + name + "\"];";
    return cb(null, code);
  };

}).call(this);
