// Generated by CoffeeScript 1.4.0
(function() {
  var css, nib, stylus, syspath;

  css = require('./css');

  syspath = require('path');

  stylus = require('stylus');

  nib = require('nib');

  exports.contentType = 'css';

  exports.process = function(txt, path, module, cb) {
    var dir, fail, succ;
    dir = syspath.dirname(path);
    succ = function(code) {
      return cb(null, css.ddns(code, module));
    };
    fail = function(err) {
      return cb(err);
    };
    return stylus.render(txt, {
      filename: path,
      paths: [dir],
      use: nib()
    }, function(err, css) {
      if (err) {
        return fail(err);
      } else {
        return succ(css);
      }
    });
  };

}).call(this);
