// Generated by CoffeeScript 1.4.0

/*
 type: dev | prd
 options: 命令行参数
*/


(function() {

  exports.exec = function(type, options, done) {
    return require('./css-md5').exec(type, options, function() {
      return require('./css-replace-domain').exec(type, options, function() {
        return require('./css-domain-mapping').exec(type, options, function() {
          return done();
        });
      });
    });
  };

}).call(this);
