// Generated by CoffeeScript 1.7.1
(function() {
  exports.getSystemDate = function() {
    return new Date();
  };

  exports.getYear = function() {
    return new Date().getFullYear();
  };

  exports.getMonth = function() {
    return new Date().getMonth() + 1;
  };

  exports.getDay = function() {
    return new Date().getDate();
  };

}).call(this);
