// Generated by CoffeeScript 1.7.1
(function() {
  exports.html = function(str) {
    return String(str).replace(/&(?!\w+;)/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  };

  exports.javascript = function(str) {
    return String(str).replace(/\\/g, '\\\\').replace(/'/g, '\\\'').replace(/"/g, '\\\"').replace(/\//g, '//');
  };

  exports.url = function(str) {
    return encodeURIComponent(str);
  };

  exports.java = function(str) {
    return String(str).replace(/\\/g, '\\\\').replace(/\"/g, '\\\"');
  };

  exports.json = function(str) {
    return String(str).replace(/\\/g, '\\\\').replace(/\"/g, '\\\"').replace(/\//g, '//');
  };

}).call(this);
