// Generated by CoffeeScript 1.4.0
(function() {
  var CHECKSUM_CACHED, cached, md5, utils;

  utils = require('../../util');

  md5 = require('MD5');

  CHECKSUM_CACHED = {};

  cached = function(filename) {
    try {
      return CHECKSUM_CACHED[filename] = md5(utils.file.io.read(filename));
    } catch (err) {

    }
  };

  /*
      加速方案
      * 将指定目录 opts.cwd 的文件按路径缓存 checksum , 在 module 初始化的时候使用该缓存
  */


  exports.init = function(options) {
    return utils.file.watch(options.cwd, function(filename) {
      return cached(filename);
    });
  };

  exports.get_checksum_cache = function(filename) {
    return CHECKSUM_CACHED[filename];
  };

  exports.init_cached = function(filename) {
    if (CHECKSUM_CACHED[filename]) {
      return;
    }
    return cached(filename);
  };

}).call(this);
