// Generated by CoffeeScript 1.4.0
(function() {
  var ModuleConfig, Package, syspath, utils;

  Package = require('../../package');

  syspath = require('path');

  utils = require('../../util');

  /* ---------------------------
      模块配置
      该配置是由指定文件的路径向上迭代得到的, 直到遇见fekit.config文件
  
      {
          //库的配置
          "lib" : {
              "core" : "./scripts/core"
          }
      }
  */


  ModuleConfig = (function() {

    function ModuleConfig(uri) {
      this.uri = uri;
      this.config = utils.config.parse(this.uri);
    }

    ModuleConfig.prototype.compileType = function() {
      return this.config.root.compiler;
    };

    ModuleConfig.prototype.isCompileTypeNormal = function() {
      return !this.config.root.compiler;
    };

    ModuleConfig.prototype.isCompileTypeModular = function() {
      return this.config.root.compiler === "modular";
    };

    ModuleConfig.prototype.isUseLibrary = function(libname) {
      return !!this.config.root.lib[libname];
    };

    ModuleConfig.prototype.parseLibrary = function(libname) {
      var path;
      path = this.config.root.lib[libname];
      if (!path) {
        return libname;
      } else {
        return syspath.join(this.config.fekit_root_dirname, path);
      }
    };

    ModuleConfig.prototype.getPackage = function(libname) {
      var p;
      p = new Package(libname, null, this.config.fekit_root_dirname);
      return p.get_local_entry();
    };

    return ModuleConfig;

  })();

  exports.ModuleConfig = ModuleConfig;

}).call(this);
