// Generated by CoffeeScript 1.4.0
(function() {
  var CSSModule, JSModule, MODULE_CONTENT_TYPE, MODULE_LINETYPE, MODULE_LINE_REGEXP, Module, ModuleConfig, ModulePath, md5, syspath, utils,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  syspath = require('path');

  utils = require('../../util');

  md5 = require("MD5");

  ModulePath = require('./path').ModulePath;

  ModuleConfig = require('./config').ModuleConfig;

  /* ---------------------------
      模块中单行类型
  */


  MODULE_LINETYPE = {
    NORMAL_LINE: 0,
    IMPORT_LINE: 1
  };

  MODULE_CONTENT_TYPE = {
    JAVASCRIPT: "javascript",
    CSS: "css"
  };

  MODULE_LINE_REGEXP = /^([^\\/]*)(@import\s+url|require)\s*\(\s*(?:["'])(.*?)(?:["'])\s*\)[\s;]*$/;

  exports.MODULE_LINE_REGEXP = MODULE_LINE_REGEXP;

  /* ---------------------------
      模块即为单一文件
  */


  Module = (function() {

    function Module(uri) {
      this.path = new ModulePath(uri);
      this.config = new ModuleConfig(uri);
      this.guid = md5(this.path.getFullPath());
      this.depends = [];
      this.sources = [];
    }

    Module.prototype._getPlaceHolder = function(line) {
      return null;
    };

    Module.prototype._check = function(line) {
      if (MODULE_LINE_REGEXP.test(line)) {
        return MODULE_LINETYPE.IMPORT_LINE;
      } else {
        return MODULE_LINETYPE.NORMAL_LINE;
      }
    };

    Module.prototype.hasDependencies = function() {
      return this.depends.length > 0;
    };

    Module.prototype.analyze = function(doneCallback) {
      var self,
        _this = this;
      self = this;
      this.sources = [];
      return this.readlines(this.path.getFullPath(), function(err, lines) {
        var line, module, _i, _len;
        for (_i = 0, _len = lines.length; _i < _len; _i++) {
          line = lines[_i];
          switch (_this._check(line)) {
            case MODULE_LINETYPE.NORMAL_LINE:
              _this.sources.push(line);
              break;
            case MODULE_LINETYPE.IMPORT_LINE:
              module = Module.parse(line, _this);
              _this.depends.push(module);
              _this.sources.push(module._getPlaceHolder(line));
          }
        }
        return doneCallback.call(self, err);
      });
    };

    Module.prototype.readlines = function(path, cb) {
      var ext, txt;
      txt = new utils.file.reader().read(path);
      ext = syspath.extname(path);
      if (ModulePath.EXTTABLE[ext]) {
        return ModulePath.EXTTABLE[ext].process(txt, path, function(err, result) {
          if (err) {
            return cb("文件编译错误 " + path + " , " + (err.toString()), []);
          } else {
            return cb(err, result.split(utils.file.NEWLINE));
          }
        });
      } else {
        return cb("找不到对应后缀名(" + ext + ")的编译方案 " + path);
      }
    };

    Module.prototype.getSourceWithoutDependencies = function() {
      return null;
    };

    Module.prototype.getDependenciesURI = function(parent_uris) {
      var m, uris, _i, _len, _ref;
      uris = parent_uris || {};
      _ref = this.depends;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        m = _ref[_i];
        uris[m.guid] = 1;
        if (m.hasDependencies()) {
          m.getDependenciesURI(uris);
        }
      }
      uris[this.guid] = 1;
      return uris;
    };

    return Module;

  })();

  Module.parse = function(line, parentModule) {
    var uri;
    if (parentModule) {
      uri = ModulePath.resolvePath(line.match(MODULE_LINE_REGEXP)[3], parentModule);
    } else {
      uri = line;
    }
    switch (ModulePath.getContentType(syspath.extname(uri))) {
      case MODULE_CONTENT_TYPE.JAVASCRIPT:
        return new JSModule(uri);
      case MODULE_CONTENT_TYPE.CSS:
        return new CSSModule(uri);
    }
  };

  Module.addExtensionPlugin = function(extName, plugin) {
    return ModulePath.addExtensionPlugin(extName, plugin);
  };

  JSModule = (function(_super) {

    __extends(JSModule, _super);

    function JSModule(uri) {
      JSModule.__super__.constructor.call(this, uri);
    }

    JSModule.prototype._getPlaceHolder = function(line) {
      var _this = this;
      if (this.config.isCompileTypeNormal()) {
        return "";
      }
      if (this.config.isCompileTypeModular()) {
        return line.replace(MODULE_LINE_REGEXP, function(match, prefix, keyword, path) {
          return "" + prefix + "__context.____MODULES['" + _this.guid + "'];";
        });
      }
      throw "找不到正确的编译方式, 请修改fekit.config中的 compiler [目前值:" + (this.config.compileType()) + "]";
    };

    JSModule.prototype._wrap = function() {
      return "\n;(function(__context){\n    var module_exports = {};\n    if( !__context.____MODULES ) { __context.____MODULES = {}; }\n    var r = (function( exports ){\n\n    " + (this.sources.join(utils.file.NEWLINE)) + "\n\n    })( module_exports );\n    if ( r ) { module_exports = r; } \n    __context.____MODULES[ \"" + this.guid + "\" ] = module_exports;\n})(this);\n";
    };

    JSModule.prototype.getSourceWithoutDependencies = function() {
      if (this.config.isCompileTypeNormal()) {
        return this.sources.join(utils.file.NEWLINE);
      }
      if (this.config.isCompileTypeModular()) {
        return this._wrap();
      }
      throw "找不到正确的编译方式, 请修改fekit.config中的 compiler [目前值:" + (this.config.compileType()) + "]";
    };

    return JSModule;

  })(Module);

  CSSModule = (function(_super) {

    __extends(CSSModule, _super);

    function CSSModule(uri) {
      CSSModule.__super__.constructor.call(this, uri);
    }

    CSSModule.prototype._getPlaceHolder = function(line) {
      return "";
    };

    CSSModule.prototype.getSourceWithoutDependencies = function() {
      return this.sources.join(utils.file.NEWLINE);
    };

    return CSSModule;

  })(Module);

  exports.Module = Module;

}).call(this);
