// Generated by CoffeeScript 1.4.0
(function() {
  var CSSModule, JSModule, MODULE_COMPILE_TYPE, MODULE_CONTENT_TYPE, Module, ModuleConfig, ModulePath, events, parser, syspath, util, utils, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  syspath = require('path');

  utils = require('../../util');

  parser = require('../parser');

  _ = require('underscore');

  util = require('util');

  events = require('events');

  ModulePath = require('./path').ModulePath;

  ModuleConfig = require('./config').ModuleConfig;

  MODULE_COMPILE_TYPE = ModuleConfig.MODULE_COMPILE_TYPE;

  MODULE_CONTENT_TYPE = {
    JAVASCRIPT: "javascript",
    CSS: "css"
  };

  /* ---------------------------
      模块即为单一文件
  */


  Module = (function() {

    function Module(uri, options) {
      var checksum;
      this.options = options;
      this.path = new ModulePath(uri);
      this.config = new ModuleConfig(uri);
      this.source = utils.file.io.read(this.path.getFullPath());
      this.depends = [];
      this.ast = null;
      if (Module.booster) {
        Module.booster.init_cached(this.path.uri);
      }
      checksum = Module.booster && Module.booster.get_checksum_cache(this.path.uri);
      this.guid = checksum || utils.md5(this.source);
      this.root_module = null;
      this.parent = null;
    }

    Module.prototype.hasDependencies = function() {
      return this.depends.length > 0;
    };

    Module.prototype.getCompileType = function() {
      var type;
      type = this.config.getCompileType();
      /* [Obsolete] 如果是组件编译模式，寻找当前模块的上级fekit.config，如果没有，则报UNKNOWN
      if type is MODULE_COMPILE_TYPE.COMPONENT
          fkconf_path = utils.path.closest @path.getFullPath() , 'fekit.config' , false , ( path ) ->
              config = utils.file.io.readJSON( path )
              config.compiler isnt 'component'
          return MODULE_COMPILE_TYPE.UNKNOWN if !fkconf_path
      
          fkconf = new ModuleConfig( fkconf_path )
          return fkconf.getCompileType()
      */

      if (type === MODULE_COMPILE_TYPE.COMPONENT) {
        return MODULE_COMPILE_TYPE.MODULAR;
      }
      return type;
    };

    Module.prototype.analyze = function(doneCallback) {
      var is_err, self;
      self = this;
      is_err = false;
      return this._process(this.path.getFullPath(), function(err, source) {
        self.ast = parser.parseAST(source);
        self.ast.find('REQUIRE', function(node) {
          var module;
          try {
            module = Module.parse(node.value, self.options, self, self.root_module);
            module.parent_module = module;
            node.module = module;
            self.depends.push(module);
            return self.analyzed();
          } catch (err) {
            is_err = true;
            return doneCallback.call(self, err);
          }
        });
        if (!is_err) {
          return doneCallback.call(self, err);
        }
      });
    };

    Module.prototype.analyzed = function() {};

    Module.prototype._process = function(path, cb) {
      var env, ext, plugin, source;
      ext = syspath.extname(path);
      plugin = ModulePath.getPlugin(ext, this.config.config.fekit_root_dirname);
      if (ext === ".json" && this.getCompileType() === MODULE_COMPILE_TYPE.NORMAL) {
        utils.logger.error("" + path + " 只支持模块化模式编译");
      }
      if (plugin) {
        source = utils.removeBOM(this.source);
        try {
          env = utils.getCurrentEnvironment(this.options);
          source = utils.replaceEnvironmentConfig('text', source, this.config.config.getEnvironmentConfig()[env]);
        } catch (err) {
          utils.logger.error("在 environment 配置中找不到 " + env);
          source = source;
        }
        return plugin.process(source, path, this, function(err, result) {
          if (err) {
            return cb("文件编译错误 " + path + " , " + (err.toString()), "");
          } else {
            return cb(err, result);
          }
        });
      } else {
        return cb("找不到对应后缀名(" + ext + ")的编译方案 " + path);
      }
    };

    Module.prototype.getSourceWithoutDependencies = function() {
      return null;
    };

    Module.prototype.getDependenciesURI = function(cb, parent_uris) {
      var self;
      self = this;
      return this.analyze(function(err) {
        var uris;
        if (err) {
          return cb(err);
        }
        uris = parent_uris || {};
        return utils.async.series(this.depends, function(m, done) {
          uris[m.guid] = 1;
          return m.getDependenciesURI(function(err, _uris) {
            if (err) {
              return done(err);
            }
            _.extend(uris, _uris);
            return done();
          }, uris);
        }, function(err) {
          uris[self.guid] = 1;
          return cb(err, uris);
        });
      });
    };

    return Module;

  })();

  Module.prototype.__proto__ = events.EventEmitter.prototype;

  Module.parse = function(path, options, parentModule, rootModule) {
    var m, uri;
    if (parentModule) {
      uri = ModulePath.resolvePath(path, parentModule);
    } else {
      uri = path;
    }
    switch (ModulePath.getContentType(syspath.extname(uri))) {
      case MODULE_CONTENT_TYPE.JAVASCRIPT:
        m = new JSModule(uri);
        break;
      case MODULE_CONTENT_TYPE.CSS:
        m = new CSSModule(uri);
    }
    if (rootModule) {
      m.root_module = rootModule;
    }
    m.parent = parentModule;
    m.options = options;
    return m;
  };

  Module.addExtensionPlugin = function(extName, plugin) {
    return ModulePath.addExtensionPlugin(extName, plugin);
  };

  Module.getContentType = function(extName) {
    return ModulePath.getContentType(extName);
  };

  Module.booster = null;

  Module.path = ModulePath;

  JSModule = (function(_super) {

    __extends(JSModule, _super);

    function JSModule(uri) {
      JSModule.__super__.constructor.call(this, uri);
    }

    JSModule.prototype.analyzed = function() {
      switch (this.getCompileType()) {
        case MODULE_COMPILE_TYPE.NORMAL:
          return this.ast.defineType('REQUIRE', function(node) {
            return "";
          });
        case MODULE_COMPILE_TYPE.MODULAR:
          return this.ast.defineType('REQUIRE', function(node) {
            return ("__context.____MODULES['" + node.module.guid + "']") + (node.is_line_end ? ";" : "");
          });
        default:
          throw "找不到正确的编译方式, 请修改fekit.config中的 compiler [目前值:" + (this.config.compileType()) + "]";
      }
    };

    JSModule.prototype._wrap = function(source) {
      return "\n;(function(__context){\n    var module = {\n        id : \"" + this.guid + "\" ,\n        filename : \"" + (syspath.basename(this.path.getFullPath())) + "\" ,\n        exports : {}\n    };\n    if( !__context.____MODULES ) { __context.____MODULES = {}; }\n    var r = (function( exports , module , global ){\n\n    " + source + "\n\n    })( module.exports , module , __context );\n    __context.____MODULES[ \"" + this.guid + "\" ] = module.exports;\n})(this);\n";
    };

    JSModule.prototype.getSourceWithoutDependencies = function() {
      switch (this.getCompileType()) {
        case MODULE_COMPILE_TYPE.NORMAL:
          return this.ast.print();
        case MODULE_COMPILE_TYPE.MODULAR:
          return this._wrap(this.ast.print());
        default:
          throw "找不到正确的编译方式, 请修改fekit.config中的 compiler [目前值:" + (this.config.compileType()) + "]";
      }
    };

    return JSModule;

  })(Module);

  CSSModule = (function(_super) {

    __extends(CSSModule, _super);

    function CSSModule(uri) {
      CSSModule.__super__.constructor.call(this, uri);
      this.iscss = true;
    }

    CSSModule.prototype.analyzed = function() {
      return this.ast.defineType('REQUIRE', function(node) {
        return "";
      });
    };

    CSSModule.prototype.getSourceWithoutDependencies = function() {
      return this.ast.print();
    };

    return CSSModule;

  })(Module);

  exports.Module = Module;

}).call(this);
