// Generated by CoffeeScript 1.4.0
(function() {
  var CONFIG, merge_user_config, utils, _;

  _ = require('underscore');

  utils = require('./util');

  CONFIG = {
    registry: 'registry.fekit.org'
  };

  merge_user_config = function() {
    var path, usr_conf;
    try {
      path = utils.path.join(utils.path.get_user_home(), ".fekitrc");
      usr_conf = utils.file.io.readJSON(path);
      return _.extend(CONFIG, usr_conf);
    } catch (err) {

    }
  };

  exports.get = function(key) {
    return CONFIG[key];
  };

  exports.each = function(cb) {
    var key, _results;
    _results = [];
    for (key in CONFIG) {
      _results.push(cb(key, CONFIG[key]));
    }
    return _results;
  };

  exports.getPackageUrl = function(name, version) {
    var registry;
    registry = CONFIG['registry'];
    registry = registry.replace(/http:\/\//, '').replace(/\/.*/, '');
    return ("http://" + registry + "/" + name + "/") + (version ? version : "");
  };

  /*
  #  返回 ~/.fekit/.extensions/ 下的已安装扩展
  #
  #  其中文件内容为,例: 
  #       svn.js     
  #           exports.path = "xxx/xxx/.js"
  #
  */


  exports.getExtensions = function() {
    var dir, list, up;
    up = utils.path;
    dir = up.join(up.get_user_home(), ".fekit", ".extensions");
    list = [];
    if (!up.exists(dir)) {
      return list;
    }
    up.each_directory(dir, (function(p) {
      var ext;
      ext = require(p);
      if (ext.path && ext.version) {
        return list.push(_.extend(ext, {
          name: up.fname(p)
        }));
      }
    }), false);
    return list;
  };

  merge_user_config();

}).call(this);
