// Generated by CoffeeScript 1.4.0
(function() {
  var compiler, jsp, minCode, pro, syspath, uglifycss, utils;

  syspath = require('path');

  compiler = require("../compiler/compiler");

  utils = require("../util");

  uglifycss = require("uglifycss");

  jsp = require("uglify-js").parser;

  pro = require("uglify-js").uglify;

  exports.get_dist_filename = function(srcpath) {
    var ext, t, _basename, _extname;
    t = compiler.getContentType(srcpath);
    switch (t.toLowerCase()) {
      case "javascript":
        ext = ".js";
        break;
      case "css":
        ext = ".css";
    }
    _extname = utils.path.extname(srcpath);
    _basename = utils.path.basename(srcpath, _extname);
    return _basename + ext;
  };

  exports.minCode = minCode = function(extname, source, options, fekitconfig) {
    var ast, final_code, _ref, _ref1, _ref10, _ref11, _ref12, _ref13, _ref14, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9;
    if (options == null) {
      options = {};
    }
    if (fekitconfig == null) {
      fekitconfig = {};
    }
    if (options.nopack) {
      return source;
    }
    switch (extname) {
      case ".css":
        if (options.noSplitCSS) {
          final_code = uglifycss.processString(source, fekitconfig != null ? (_ref = fekitconfig.min) != null ? (_ref1 = _ref.config) != null ? _ref1.uglifycss : void 0 : void 0 : void 0);
        } else {
          final_code = uglifycss.processString(source, fekitconfig != null ? (_ref2 = fekitconfig.min) != null ? (_ref3 = _ref2.config) != null ? _ref3.uglifycss : void 0 : void 0 : void 0).replace(/}/g, "}\n");
        }
        break;
      case ".js":
        try {
          ast = jsp.parse(source);
          ast = pro.ast_mangle(ast, fekitconfig != null ? (_ref4 = fekitconfig.min) != null ? (_ref5 = _ref4.config) != null ? (_ref6 = _ref5.uglifyjs) != null ? _ref6.ast_mangle : void 0 : void 0 : void 0 : void 0);
          if (fekitconfig != null ? (_ref7 = fekitconfig.minconfig) != null ? (_ref8 = _ref7.uglifyjs) != null ? _ref8.ast_squeeze : void 0 : void 0 : void 0) {
            ast = pro.ast_squeeze(ast, fekitconfig != null ? (_ref9 = fekitconfig.min) != null ? (_ref10 = _ref9.config) != null ? (_ref11 = _ref10.uglifyjs) != null ? _ref11.ast_squeeze : void 0 : void 0 : void 0 : void 0);
          }
          final_code = pro.gen_code(ast, fekitconfig != null ? (_ref12 = fekitconfig.min) != null ? (_ref13 = _ref12.config) != null ? (_ref14 = _ref13.uglifyjs) != null ? _ref14.gen_code : void 0 : void 0 : void 0 : void 0);
        } catch (err) {
          console.info(err);
          return null;
        }
    }
    return final_code;
  };

}).call(this);
