// Generated by CoffeeScript 1.4.0
(function() {
  var http, httpProxy, sysurl, utils;

  utils = require("../util");

  sysurl = require('url');

  http = require('http');

  httpProxy = require('http-proxy');

  exports.run = function(options) {
    var port, proxy, rule, server;
    if (!options.proxy) {
      return;
    }
    rule = options.rule;
    if (!rule) {
      return;
    }
    port = rule.http_port || 10180;
    proxy = httpProxy.createProxyServer({});
    proxy.on('error', function(err, req, res) {
      res.writeHead(500, {
        'Content-Type': 'text/plain'
      });
      return res.end('[HTTP PROXY ERROR]' + err.toString());
    });
    server = http.createServer(function(req, res) {
      var r, u;
      u = sysurl.parse(req.url);
      r = rule.match(u);
      if (r) {
        if (r.getURL()) {
          req.url = r.getURL();
        }
        return proxy.web(req, res, {
          target: r.getFullHost()
        });
      } else {
        return proxy.web(req, res, {
          target: u.protocol + "//" + u.host
        });
      }
    });
    utils.logger.log("fekit proxy server 运行成功, 端口为 " + port + ".");
    return server.listen(port);
  };

}).call(this);
