// Generated by CoffeeScript 1.4.0
(function() {

  exports.usage = "TAB 自动补全";

  exports.run = function(options) {
    if (process.platform === "darwin") {
      console.error("fekit completion 不支持 windows");
      return null;
    }
  };

}).call(this);
