// Generated by CoffeeScript 1.4.0
(function() {
  var env, r, show, utils;

  utils = require('../util');

  env = require('../env');

  r = console.info;

  show = function() {
    r("\n");
    env.each(function(key, value) {
      return r(";   " + key + "  =  \"" + value + "\"");
    });
    return r("\n");
  };

  exports.usage = "显示 fekit 的配置项";

  exports.set_options = function(optimist) {
    optimist.alias('s', 'set');
    optimist.describe('s', '增加一个配置项 fekit -s [key] [value]');
    optimist.alias('d', 'delete');
    return optimist.describe('d', '删除一个配置项 fekit -d [key]');
  };

  exports.run = function(options) {
    var key, val;
    if (options.set && options._[0] === 'config' && options._[1]) {
      key = options.set;
      val = options._[1] || 0;
      env.set(key, val);
      return utils.logger.log("已设置 " + key + " 为 " + val);
    } else if (options['delete']) {
      key = options['delete'];
      env.del(key);
      return utils.logger.log("已删除 " + key);
    } else {
      return show();
    }
  };

}).call(this);
