// Generated by CoffeeScript 1.3.3
(function() {
  var env, r;

  env = require('../env');

  r = console.info;

  exports.usage = "显示 fekit 的配置项";

  exports.set_options = function(optimist) {
    return optimist;
  };

  exports.run = function(options) {
    r("\n");
    env.each(function(key, value) {
      return r(";   " + key + "  =  \"" + value + "\"");
    });
    return r("\n");
  };

}).call(this);
