// Generated by CoffeeScript 1.4.0
(function() {
  var config_object, do_clean, do_export, start_export, syspath, utils;

  syspath = require('path');

  utils = require('../util');

  exports.usage = "自动化生成 fekit.config 'export' 列表";

  config_object = {};

  do_clean = function(dir) {
    var exists, i, nu, _i, _len, _ref;
    nu = [];
    exists = function(path) {
      if (path.path != null) {
        path = path.path;
      }
      return utils.path.exists(utils.path.join(dir, path));
    };
    _ref = config_object["export"];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      if (exists(i)) {
        nu.push(i);
      }
    }
    return config_object["export"] = nu;
  };

  start_export = function(dir) {
    return utils.path.each_directory(dir, function(file) {
      if (utils.path.is_directory(file)) {
        start_export(file, dir);
        return null;
      }
      if (~file.indexOf(".js" || ~file.indexOf(".css"))) {
        return do_export(file, dir);
      }
    }, true);
  };

  do_export = function(file, dir) {
    var content, lines, reader;
    reader = new utils.file.reader();
    content = reader.read(file);
    lines = content.split("\n");
    file = syspath.relative(dir, file);
    return console.log(file);
  };

  exports.run = function(options) {
    var base, config_file, dir, reader, str, writer;
    base = options.cwd;
    dir = options._[1] || 'src';
    dir = utils.path.join(base, dir);
    config_file = utils.path.join(base, 'fekit.config');
    reader = new utils.file.reader();
    try {
      config_object = reader.readJSON(config_file);
    } catch (err) {
      return utils.logger.error(err);
    }
    do_clean(dir);
    start_export(dir);
    str = JSON.stringify(config_object, null, 4);
    writer = new utils.file.writer();
    return writer.write(config_file, str);
  };

}).call(this);
