// Generated by CoffeeScript 1.4.0
(function() {
  var async, env, prompt, utils, _;

  env = require('../env');

  utils = require('../util');

  _ = require('underscore');

  async = require('async');

  prompt = require('prompt');

  exports.usage = "登出";

  exports.set_options = function(optimist) {
    return optimist;
  };

  exports.run = function(options) {
    var user;
    user = env.get("user");
    if (!user) {
      return utils.logger.log("尚未登录");
    }
    utils.file.rmrf(utils.path.join(utils.path.get_user_home(), ".fekit.pas"));
    env.del("user");
    return utils.logger.log("" + user + " 已登出成功");
  };

}).call(this);
