// Generated by CoffeeScript 1.7.1
(function() {
  var async, env, utils;

  async = require('async');

  utils = require('../util');

  env = require('../env');

  exports.usage = "安装或删除插件";

  exports.set_options = function(optimist) {
    optimist.alias('i', 'install');
    optimist.describe('i', '安装插件');
    optimist.alias('u', 'uninstall');
    return optimist.describe('u', '删除插件');
  };

  exports.run = function(options) {
    var dirpath;
    dirpath = utils.path.join(utils.path.get_user_home(), ".fekit", ".extensions");
    utils.file.mkdirp(dirpath);
    if (options.install) {
      utils.proc.spawn('npm', ['install', 'fekit-extension-' + options.install, '-g'], function() {
        utils.logger.log('安装完成.');
        return utils.exit;
      });
    }
    if (options.uninstall) {
      return utils.proc.spawn('npm', ['uninstall', 'fekit-extension-' + options.install, '-g'], function() {
        utils.logger.log('删除完成.');
        return utils.exit;
      });
    }
  };

}).call(this);
