// Generated by CoffeeScript 1.4.0
(function() {
  var proxy;

  proxy = require("mitm-proxy");

  exports.usage = "创建http代理服务器 , 默认端口10086";

  exports.set_options = function(optimist) {
    optimist.alias('p', 'port');
    return optimist.describe('p', '自定义代理服务的服务端口号');
  };

  exports.run = function(options) {
    var proxyPort;
    proxyPort = options.port || 10086;
    new proxy({
      proxy_port: proxyPort,
      mitm_port: "10012",
      verbose: true
    });
    console.log("[LOG]: fekit proxy 运行成功, 端口为 " + proxyPort + ".");
    return console.log("[LOG]: 按 Ctrl + C 结束进程.");
  };

}).call(this);
