// Generated by CoffeeScript 1.4.0
(function() {

  exports.usage = "发布 fekit 组件 ";

  exports.set_options = function(optimist) {
    return optimist;
  };

  exports.run = function(options) {};

}).call(this);
