// Generated by CoffeeScript 1.4.0
(function() {
  var spawn, utils;

  utils = require('../util');

  spawn = require('child_process').spawn;

  exports.usage = "进行单元测试";

  exports.set_options = function(optimist) {
    return optimist;
  };

  exports.run = function(options) {
    var c, p;
    p = utils.path.join(__dirname, '../../node_modules/.bin/mocha');
    c = spawn('node', [p, '--colors', '--recursive', '--compilers', 'coffee:coffee-script'], {
      cwd: options.cwd,
      env: process.env
    });
    c.stderr.pipe(process.stderr, {
      end: false
    });
    return c.stdout.pipe(process.stdout, {
      end: false
    });
  };

}).call(this);
