// Generated by CoffeeScript 1.4.0
(function() {
  var spawn, utils;

  utils = require('../util');

  spawn = require('child_process').spawn;

  exports.usage = "进行单元测试";

  exports.set_options = function(optimist) {
    return optimist;
  };

  exports.run = function(options) {
    var c, errmsg;
    errmsg = '';
    c = spawn(utils.proc.npmbin("mocha"), ['--colors', '--recursive', '--compilers', 'coffee:coffee-script'], {
      cwd: options.cwd,
      env: process.env
    });
    c.stderr.on('data', function(data) {
      return errmsg += data;
    });
    c.stderr.on('close', function(err) {
      if (errmsg) {
        utils.logger.error("请建立`test`目录，并放置测试用例");
      }
      if (options.debug) {
        return utils.logger.error(errmsg);
      }
    });
    return c.stdout.pipe(process.stdout, {
      end: false
    });
  };

}).call(this);
