// Generated by CoffeeScript 1.4.0
(function() {
  var async, env, request, semver, utils, _;

  env = require('../env');

  request = require('request');

  utils = require('../util');

  _ = require('underscore');

  async = require('async');

  semver = require('semver');

  exports.usage = "取消发布特定的组件包";

  exports.set_options = function(optimist) {
    optimist.usage('unpublish name[@version]');
    return optimist;
  };

  exports.run = function(options) {
    var name, spec_pkg, url, version;
    spec_pkg = options['_'][1];
    if (!spec_pkg) {
      return utils.logger.error('请指定要取消发布的包及版本号.');
    }
    name = spec_pkg.split('@')[0];
    version = spec_pkg.split('@')[1];
    if (~spec_pkg.indexOf('@')) {
      if (!semver.valid(version)) {
        return utils.logger.error('请指定正确的版本号.');
      }
    }
    url = env.getPackageUrl(name, version);
    return utils.http.del(url, function(err, res, body) {
      var data;
      data = JSON.parse(body);
      if (!data.ret) {
        return utils.logger.error(data.errmsg);
      }
      return utils.logger.log("" + name + " @ " + (version || "all") + " 删除成功");
    });
  };

}).call(this);
