// Generated by CoffeeScript 1.4.0
(function() {
  var async, env, utils;

  async = require('async');

  utils = require('../util');

  env = require('../env');

  exports.usage = "更新自身及更新已安装扩展";

  exports.set_options = function(optimist) {
    return optimist;
  };

  exports.run = function(options) {
    var i, npm, tasks, _i, _len, _ref;
    npm = (process.platform === "win32" ? "npm.cmd" : "npm");
    tasks = [];
    _ref = env.getExtensions();
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      i = _ref[_i];
      tasks.push((function(name) {
        return function(done) {
          return utils.proc.spawn(npm, ['install', 'fekit-extension-' + name, '-g'], function() {
            return done();
          });
        };
      })(i.name));
    }
    tasks.push(function(done) {
      return utils.proc.spawn(npm, ['install', 'fekit', '-g'], function() {
        return done();
      });
    });
    return async.series(tasks, function(err) {
      if (err) {
        return utils.logger.error(err);
      }
      return utils.logger.log('升级完成.');
    });
  };

}).call(this);
